### PR TITLE
GABLS3 Updating for LSM and with ThtIL Advection

### PR DESCRIPTION
**Pull request by ddamicoWX10**

### CODE REVIEW

**Comment by grantfirl** [comment]
@ddamicoWX10 Since my branch (https://github.com/grantfirl/gmtb-scm/tree/add_GABLS3) contains more changes to get this to work, this PR should be pointed there, not NCAR/master. Once the changes are collected in my fork, I'll submit a PR to NCAR/master.

**Comment by ddamicoWX10** [comment]
> @ddamicoWX10 Since my branch (https://github.com/grantfirl/gmtb-scm/tree/add_GABLS3) contains more changes to get this to work, this PR should be pointed there, not NCAR/master. Once the changes are collected in my fork, I'll submit a PR to NCAR/master.

@grantfirl My apologies. Still learning Github. Should I close this pull request and open one in your fork?

**Comment by grantfirl** [comment]
No problem, and yes, please -- to the add_GABLS3 branch in my fork. Also, I'd like to only have one script for generating the case data file. This PR has new_gabls3.ncl and GABLS3_LSM.ncl. Only the latter is needed, right?

**Comment by ddamicoWX10** [comment]
Yes, only the latter is needed.

**Pull request closed without merging**
