### PR TITLE
add Dockerhub instructions content to Users Guide

### PR DESCRIPTION
**Pull request by grantfirl**
- Add Dockerhub instructions
- rearrange Cheyenne setup scripts to execute module loads after being in python environment
- remove need to have f90nml source in scm repo by using pip install statements on hera (from GitHub) and cheyenne (from default pip index)
- modify instructions for installing f90nml on other machines

### CODE REVIEW

**Comment by climbfuji** [comment]
@grantfirl does this address the issue on Cheyenne that was reported earlier today? No need anymore for me to figure this out?

**Comment by grantfirl** [comment]
I think so, yes.

**Comment by climbfuji** [comment]
> I think so, yes.
> […](#)

Thanks!

**Comment by grantfirl** [comment]
Ok, thanks. Ya, i quit for the day before actually testing that PR. Will do
so and correct mistakes this morning.

**Comment by climbfuji** [comment]
I assume you are still working on this? I see that the Cheyenne GNU csh script is a cleaned up update, versus the sh script still moves everything around?

**Comment by grantfirl** [comment]
Yes, I'm testing the .csh versions now. The .sh versions will be updated afterward.

**Comment by grantfirl** [comment]
OK, @climbfuji, this should be good to test. Everything worked for me. I deactivated the python environment, removed the environment clone, and did a module purge between each script's test and it worked fine. I could also switch among intel/gnu without issue.

**Comment by grantfirl** [comment]
Tested Hera changes as well. No issues for me.

**Pull request merged**
