### PR TITLE
Update SCM to work with gmtb/develop branch of ccpp-physics

### PR DESCRIPTION
**Pull request by grantfirl**
update CCPP SDFs, physics namelists, ccpp_prebuild_config.py, GFS_typedefs.[F90,meta], gmtb_scm_setup, gmtb_scm_type_defs to work with latest gmtb/develop branch of ccpp-physics; requires CIRES UGWP namelist fix

This incorporates changes to ccpp-physics as of 23 Oct 2019.

works with ccpp-physics PR:
https://github.com/NCAR/ccpp-physics/pull/343

### CODE REVIEW

**Comment by climbfuji** [comment]
@grantfirl The two physics PRs have the "do not merge" labels, I assume this PR should also be labeled as such? What is your intended strategy for merging those?

**Comment by grantfirl** [comment]
> @grantfirl The two physics PRs have the "do not merge" labels, I assume this PR should also be labeled as such? What is your intended strategy for merging those?

OK, added "do not merge". The intended strategy was to run the full gamut of RTs for them. Somehow the RTs with the GWD interstitial code reorg were failing several of the tests in rt_ccpp_gmtb.conf in verify mode, so I'm investigating that. I'm completely lost with where everything is going with code management, so I'll need a refresher.

**Comment by grantfirl** [comment]
With commit 06362e0, this PR is no longer dependent on https://github.com/NCAR/ccpp-physics/pull/342

**Comment by grantfirl** [comment]
@climbfuji @ligiabernardet This PR for the SCM needs to be merged ASAP since others are wanting to use the latest physics and code features. The GWD interstitial reorganization PROD mode RT failure was holding this up, but I removed the dependence on that PR, so this should be good to go. It still depends on NCAR/ccpp-physics#343, and I'm running the full rt.conf with that PR with FV3 right now, and I expect it to pass since it's only changing the namelist filename in cires_ugwp to work like GFDL MP.

**Pull request merged**
