### PR TITLE
release/public-v4: disable dynamic build, NCEPLIBS update, doc update

### PR DESCRIPTION
**Pull request by climbfuji**
- disable dynamic build
- provide simple shell script to install required NCEPLIBS in a separate directory (specified as argument on the command line)

### CODE REVIEW

**Comment by grantfirl** [comment]
@climbfuji Please see https://github.com/grantfirl/gmtb-scm/tree/release/public-v4

**Comment by grantfirl** [comment]
The machine setup scripts for Hera and Cheyenne are updated in my branch. I'll go ahead and change the Users Guide to reflect no dynamic mode. Thanks for changing CMakeLists.txt to make it default already.

**Comment by climbfuji** [comment]
@grantfirl Please have a look and see if it does the job for you on your different test systems. Thanks!

Note: this does not contain any changes to the setup scripts in scm/etc/ !

**Comment by climbfuji** [comment]
What I did on my mac:
```
export CC=gcc-9
export FC=gfortran-9
export CXX=g++-9
./contrib/build_nceplibs.sh $PWD/nceplibs
export BACIO_LIB4=/Users/dom.heinzeller/scratch/gmtb-scm/gmtb-scm-public-release-20200305/nceplibs/lib/libbacio_v2.2.0_4.a
export SP_LIBd=/Users/dom.heinzeller/scratch/gmtb-scm/gmtb-scm-public-release-20200305/nceplibs/lib/libsp_v2.1.0_d.a
export W3NCO_LIBd=/Users/dom.heinzeller/scratch/gmtb-scm/gmtb-scm-public-release-20200305/nceplibs/lib/libw3nco_v2.1.0_d.a
mkdir scm/bin
cd scm/bin
cmake ../src 2>&1 | tee log.cmake
make VERBOSE=1 2>&1 | tee log.make
```

**Comment by grantfirl** [comment]
Thanks, @climbfuji, will give it a shot...

**Comment by grantfirl** [comment]
@climbfuji It works wonders. So, if users don't already have cmake v3.15+, they'll need to upgrade. This is a higher required version than the rest of the SCM, but I don't think it's a big deal.

**Comment by grantfirl** [comment]
@climbfuji Just to be clear, the machine setup scripts in scm/etc for Hera and Cheyenne can continue just to load preinstalled libraries, right? I.e., only setup scripts for mac, and linux flavors should need to do this.

**Comment by climbfuji** [comment]
> @climbfuji Just to be clear, the machine setup scripts in scm/etc for Hera and Cheyenne can continue just to load preinstalled libraries, right? I.e., only setup scripts for mac, and linux flavors should need to do this.

Yes, that's correct. Only for supported but not preconfigured platforms (to use the lingo of the UFS). Glad that it works for you. Sorry that I forgot about the cmake version. I don't think there is much we can do except providing a recent cmake version to build/install as part of the SCM, or provide the instructions for doing it. NCEPLIBS-external ships cmake 3.16.3 for users who don't have a recent cmake version. Let me know if you think we should do this or just tell the user to get it elsewhere ...

**Comment by climbfuji** [comment]
@grantfirl should I merge this PR?

**Pull request merged**
