### PR TITLE
Update for Mike Iacono's RRTMG cloud overlap code

### PR DESCRIPTION
**Pull request by grantfirl**
This PR matches https://github.com/NOAA-EMC/fv3atm/pull/157 for the updated cloud overlap for RRTMG from Mike Iacono (AER).

Associated PRs:
https://github.com/NOAA-EMC/fv3atm/pull/157
https://github.com/NCAR/ccpp-physics/pull/487

This effectively replaces #188.

### CODE REVIEW

**Comment by grantfirl** [comment]
This code has been tested to build/compile/run with https://github.com/NCAR/ccpp-physics/pull/487.

I ran the TWPICE maritime deep convective case using the default cloud overlap namelist parameters and setting both SW and LW overlap methods to 4 and 5. All ran, with very minor differences for this case (see attached plots).
[profiles_mean_dT_dt_lwrad.pdf](https://github.com/NCAR/gmtb-scm/files/5059710/profiles_mean_dT_dt_lwrad.pdf)
[profiles_mean_dT_dt_swrad.pdf](https://github.com/NCAR/gmtb-scm/files/5059711/profiles_mean_dT_dt_swrad.pdf)
[profiles_mean_T.pdf](https://github.com/NCAR/gmtb-scm/files/5059712/profiles_mean_T.pdf)

**Comment by grantfirl** [comment]
> Looks good to me. Will have to wait, though, until we can merge the ccpp-physics PR.

Yep, will do. I'll update the ccpp-physics submodule pointer when that PR is merged before merging this.

**Comment by grantfirl** [comment]
@climbfuji @llpcarson Now that https://github.com/NOAA-EMC/fv3atm/pull/157 is merged, this should be good to go to.

**Review by climbfuji — APPROVED** [review]
Looks familiar!

**Pull request merged**
