### PR TITLE
changes to SCM for RRTMGP

### PR DESCRIPTION
**Pull request by grantfirl**
This PR contains the following:

Started from commit e860c96 of the rrtmgp-dev2 branch of dustinswales fork: https://github.com/dustinswales/gmtb-scm-1/tree/rrtmgp-dev2

Merged in the code from PR #176 (contains v4 release code merged with dtc/develop branch).

Followed PRs https://github.com/NCAR/fv3atm/pull/32 and https://github.com/NCAR/ufs-weather-model/pull/29 to work with PRs https://github.com/NCAR/ccpp-framework/pull/270 and https://github.com/NCAR/ccpp-physics/pull/411:

- edited ccpp_prebuild_config.py to match changes in FV3's
- added do_RRTMGP and edited rrtmgp_root in RRTMGP suite namelist
- edited RRTMGP SDF (suite name, removed dcyc2t3_post, version #)
- edited GFS_typedefs.[F90,meta] to match FV3's
- remove RRTMGP types from gmtb_scm_type_defs.[F90,meta] (moved to Interstitial DDT in GFS_typedefs to match FV3)

### CODE REVIEW

**Comment by grantfirl** [comment]
Running the TWPICE case with suites SCM_GFS_v15p2 and SCM_GFS_v15_RRTMGP:

mean SW and LW temperature tendencies over active period (green uses RRTMGP):
[profiles_mean_dT_dt_swrad.pdf](https://github.com/NCAR/gmtb-scm/files/4362293/profiles_mean_dT_dt_swrad.pdf)
[profiles_mean_dT_dt_lwrad.pdf](https://github.com/NCAR/gmtb-scm/files/4362298/profiles_mean_dT_dt_lwrad.pdf)


Resultant changes in temperature tendencies due to other processes:

[profiles_mean_multi_T_forcing.pdf](https://github.com/NCAR/gmtb-scm/files/4362296/profiles_mean_multi_T_forcing.pdf)

**Comment by grantfirl** [comment]
Updated to work with fixed FV3-based PRs. The results from the TWPICE case are actually quite different, but still reasonable:

[profiles_mean_dT_dt_lwrad.pdf](https://github.com/NCAR/gmtb-scm/files/4384282/profiles_mean_dT_dt_lwrad.pdf)
[profiles_mean_dT_dt_swrad.pdf](https://github.com/NCAR/gmtb-scm/files/4384283/profiles_mean_dT_dt_swrad.pdf)
[profiles_mean_multi_T_forcing.pdf](https://github.com/NCAR/gmtb-scm/files/4384284/profiles_mean_multi_T_forcing.pdf)

**Comment by grantfirl** [comment]
> The changes I am seeing look good to me, but I am surprised I don't see any changes to the build system. If you are using the new capability (include auto-generated CCPP_TYPDEFS.{mk,cmake,sh}) then you can probably remove some files from gmtb-scm's CMakeLists.txt. Like in the fv3atm PR?

OK, I'll look at this tomorrow. It seems to work as is, but I'm sure that it could probably be streamlined. As you know, I'm not a build system connoisseur.

**Comment by climbfuji** [comment]
> > The changes I am seeing look good to me, but I am surprised I don't see any changes to the build system. If you are using the new capability (include auto-generated CCPP_TYPDEFS.{mk,cmake,sh}) then you can probably remove some files from gmtb-scm's CMakeLists.txt. Like in the fv3atm PR?
> 
> OK, I'll look at this tomorrow. It seems to work as is, but I'm sure that it could probably be streamlined. As you know, I'm not a build system connoisseur.

I can do that for you if you like and create a PR for your branch.

**Comment by climbfuji** [comment]
> > > The changes I am seeing look good to me, but I am surprised I don't see any changes to the build system. If you are using the new capability (include auto-generated CCPP_TYPDEFS.{mk,cmake,sh}) then you can probably remove some files from gmtb-scm's CMakeLists.txt. Like in the fv3atm PR?
> > 
> > 
> > OK, I'll look at this tomorrow. It seems to work as is, but I'm sure that it could probably be streamlined. As you know, I'm not a build system connoisseur.
> 
> I can do that for you if you like and create a PR for your branch.

@grantfirl please let me know if you want me to work on this. Thanks!

**Comment by grantfirl** [comment]
> > > > The changes I am seeing look good to me, but I am surprised I don't see any changes to the build system. If you are using the new capability (include auto-generated CCPP_TYPDEFS.{mk,cmake,sh}) then you can probably remove some files from gmtb-scm's CMakeLists.txt. Like in the fv3atm PR?
> > > 
> > > 
> > > OK, I'll look at this tomorrow. It seems to work as is, but I'm sure that it could probably be streamlined. As you know, I'm not a build system connoisseur.
> > 
> > 
> > I can do that for you if you like and create a PR for your branch.
> 
> @grantfirl please let me know if you want me to work on this. Thanks!

That'd be great if you have the time. All I saw in the fv3atm PR for CMakeLists.txt was one added line.

**Comment by climbfuji** [comment]
> > > > > The changes I am seeing look good to me, but I am surprised I don't see any changes to the build system. If you are using the new capability (include auto-generated CCPP_TYPDEFS.{mk,cmake,sh}) then you can probably remove some files from gmtb-scm's CMakeLists.txt. Like in the fv3atm PR?
> > > > 
> > > > 
> > > > OK, I'll look at this tomorrow. It seems to work as is, but I'm sure that it could probably be streamlined. As you know, I'm not a build system connoisseur.
> > > 
> > > 
> > > I can do that for you if you like and create a PR for your branch.
> > 
> > 
> > @grantfirl please let me know if you want me to work on this. Thanks!
> 
> That'd be great if you have the time. All I saw in the fv3atm PR for CMakeLists.txt was one added line.

In https://github.com/NCAR/fv3atm/pull/32/files look for the various CMakeLists.txt and makefile changes. But no worries, I will give it a try. Going to check out your grant-rrtmgp branch now, please don't make any changes for the time being.

**Comment by grantfirl** [comment]
IMO, this is ready to merge once we have approval from other codeowners.

**Pull request merged**
