### PR TITLE
Update for v4.1 CCPP release

### PR DESCRIPTION
**Pull request by grantfirl**
- updated submodule pointers for latest release/public-v4 branches of ccpp-physics and ccpp-framework
- updated machine setup scripts to match those in release branch of ufs-weather-model
- include change for using anaconda python on Hera (that already exists in master)

This update has been tested successfully on Hera/intel (prod/debug), Cheyenne/intel (prod/debug), Cheyenne/gnu (prod/debug), Mac clang/gnu9.1

### CODE REVIEW

**Comment by grantfirl** [comment]
OK, I'll update the SCM, retest with gfortran-10, and submit a new PR afterward.

**Comment by climbfuji** [comment]
Turns out I only needed to make changes in fv3atm and ufs-weather-model, not in ccpp-physics. You may have to do the same in gmtb-scm. See here: https://github.com/ufs-community/ufs-weather-model/pull/186

**Comment by climbfuji** [comment]
Do you have the ability to test with gfortran-10?

**Comment by grantfirl** [comment]
> Do you have the ability to test with gfortran-10?

Yes, if it is available on Cheyenne or Hera. Maybe, with the help of sys admins, if I have to upgrade on my Mac since I lack admin privileges.

**Comment by climbfuji** [comment]
> > Do you have the ability to test with gfortran-10?
> 
> Yes, if it is available on Cheyenne or Hera. Maybe, with the help of sys admins, if I have to upgrade on my Mac since I lack admin privileges.

I can test it for you on my test laptop.

**Comment by climbfuji** [comment]
I see that cheyenne has gnu-10.1.0.

**Pull request merged**
